//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiffChallengeDraft.Cli {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Texts() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiffChallengeDraft.Cli.Texts", typeof(Texts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All contestants drawn! Moving on....
        /// </summary>
        public static string DRAFT_ALL_DRAWN_MOVING_ON {
            get {
                return ResourceManager.GetString("DRAFT_ALL_DRAWN_MOVING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Another?.
        /// </summary>
        public static string DRAFT_ANOTHER {
            get {
                return ResourceManager.GetString("DRAFT_ANOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Riff challenge determination.
        /// </summary>
        public static string DRAFT_CHALLENGE_OVERVIEW {
            get {
                return ResourceManager.GetString("DRAFT_CHALLENGE_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contestant drawn.
        /// </summary>
        public static string DRAFT_CONTESTANT_DRAWN {
            get {
                return ResourceManager.GetString("DRAFT_CONTESTANT_DRAWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name of contestant number.
        /// </summary>
        public static string DRAFT_CONTESTANT_NUMBER {
            get {
                return ResourceManager.GetString("DRAFT_CONTESTANT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Now on to the draft..
        /// </summary>
        public static string DRAFT_CONTINUE {
            get {
                return ResourceManager.GetString("DRAFT_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to We&apos;re now going to gather information about the contestants..
        /// </summary>
        public static string DRAFT_INFORMATION {
            get {
                return ResourceManager.GetString("DRAFT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contestants list.
        /// </summary>
        public static string DRAFT_INITIAL_PARTICIPANTS {
            get {
                return ResourceManager.GetString("DRAFT_INITIAL_PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} will challenge {1}, and is challenged by {2}.
        /// </summary>
        public static string DRAFT_TEMPLATE_PARTICIPANT_WILL_CHALLENGE {
            get {
                return ResourceManager.GetString("DRAFT_TEMPLATE_PARTICIPANT_WILL_CHALLENGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aaaaaaaand, WE&apos;RE DONE! Thanks for tuning in, see you next week!.
        /// </summary>
        public static string ENDING_TEXT {
            get {
                return ResourceManager.GetString("ENDING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Log can be found here.
        /// </summary>
        public static string LOG_CAN_BE_FOUND_HERE {
            get {
                return ResourceManager.GetString("LOG_CAN_BE_FOUND_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stream/Secretary draft.
        /// </summary>
        public static string NEXTDRAFT_HEADLINE {
            get {
                return ResourceManager.GetString("NEXTDRAFT_HEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Secretary is going to be.
        /// </summary>
        public static string NEXTDRAFT_SECRETARY_IS {
            get {
                return ResourceManager.GetString("NEXTDRAFT_SECRETARY_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Streamer is going to be.
        /// </summary>
        public static string NEXTDRAFT_STREAMER_IS {
            get {
                return ResourceManager.GetString("NEXTDRAFT_STREAMER_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order is determined! Now on to the theme week lottery..
        /// </summary>
        public static string ORDER_DETERMINED_ON_TO_THEME {
            get {
                return ResourceManager.GetString("ORDER_DETERMINED_ON_TO_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to What is it going to be? The choices are.
        /// </summary>
        public static string THEME_CHOICES_ARE {
            get {
                return ResourceManager.GetString("THEME_CHOICES_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NO.
        /// </summary>
        public static string THEME_NO {
            get {
                return ResourceManager.GetString("THEME_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The theme pick is:.
        /// </summary>
        public static string THEME_PICK_IS {
            get {
                return ResourceManager.GetString("THEME_PICK_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Is it theme week?.
        /// </summary>
        public static string THEME_QUESTION {
            get {
                return ResourceManager.GetString("THEME_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s going to be: {0}! Congratulations..
        /// </summary>
        public static string THEME_TEMPLATE_PARTICIPANT_PICK {
            get {
                return ResourceManager.GetString("THEME_TEMPLATE_PARTICIPANT_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Which contestant is going to get his {0} theme idea of the week?.
        /// </summary>
        public static string THEME_TEMPLATE_WHICH_CONTESTANT {
            get {
                return ResourceManager.GetString("THEME_TEMPLATE_WHICH_CONTESTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Theme week.
        /// </summary>
        public static string THEME_WEEK {
            get {
                return ResourceManager.GetString("THEME_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to YES.
        /// </summary>
        public static string THEME_YES {
            get {
                return ResourceManager.GetString("THEME_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Welcome to the Riff Challenge Draft CLI 2000!.
        /// </summary>
        public static string WELCOME_TEXT {
            get {
                return ResourceManager.GetString("WELCOME_TEXT", resourceCulture);
            }
        }
    }
}
