//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiffChallengeDraft {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiffChallengeDraft.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contestants drawn! Moving on....
        /// </summary>
        internal static string DRAFT_ALL_DRAWN_MOVING_ON {
            get {
                return ResourceManager.GetString("DRAFT_ALL_DRAWN_MOVING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another?.
        /// </summary>
        internal static string DRAFT_ANOTHER {
            get {
                return ResourceManager.GetString("DRAFT_ANOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contestant drawn.
        /// </summary>
        internal static string DRAFT_CONTESTANT_DRAWN {
            get {
                return ResourceManager.GetString("DRAFT_CONTESTANT_DRAWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of contestant number.
        /// </summary>
        internal static string DRAFT_CONTESTANT_NUMBER {
            get {
                return ResourceManager.GetString("DRAFT_CONTESTANT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re now going to gather information about the contestants..
        /// </summary>
        internal static string DRAFT_INFORMATION {
            get {
                return ResourceManager.GetString("DRAFT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will challenge {1}, and is challenged by {2}.
        /// </summary>
        internal static string DRAFT_TEMPLATE_PARTICIPANT_WILL_CHALLENGE {
            get {
                return ResourceManager.GetString("DRAFT_TEMPLATE_PARTICIPANT_WILL_CHALLENGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now on to the draft..
        /// </summary>
        internal static string DRAW_ON_TO_DRAFT {
            get {
                return ResourceManager.GetString("DRAW_ON_TO_DRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaaaaaaand, WE&apos;RE DONE! Thanks for tuning in, see you next week!.
        /// </summary>
        internal static string ENDING_TEXT {
            get {
                return ResourceManager.GetString("ENDING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is determined! Now on to the wildcard week lottery..
        /// </summary>
        internal static string ORDER_DETERMINED_ON_TO_WILDCARD {
            get {
                return ResourceManager.GetString("ORDER_DETERMINED_ON_TO_WILDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Riff Challenge Draft CLI 2000!.
        /// </summary>
        internal static string WELCOME_TEXT {
            get {
                return ResourceManager.GetString("WELCOME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is it going to be? The choices are.
        /// </summary>
        internal static string WILDCARD_CHOICES_ARE {
            get {
                return ResourceManager.GetString("WILDCARD_CHOICES_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, sorry. Better luck next week..
        /// </summary>
        internal static string WILDCARD_NO {
            get {
                return ResourceManager.GetString("WILDCARD_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wildcard choice is:.
        /// </summary>
        internal static string WILDCARD_PICK_IS {
            get {
                return ResourceManager.GetString("WILDCARD_PICK_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it wildcard week?.
        /// </summary>
        internal static string WILDCARD_QUESTION {
            get {
                return ResourceManager.GetString("WILDCARD_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s going to be: {0}! Congratulations..
        /// </summary>
        internal static string WILDCARD_TEMPLATE_PARTICIPANT_PICK {
            get {
                return ResourceManager.GetString("WILDCARD_TEMPLATE_PARTICIPANT_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which contestant is going to get his {0} wildcard pick of the week?.
        /// </summary>
        internal static string WILDCARD_TEMPLATE_WHICH_CONTESTANT {
            get {
                return ResourceManager.GetString("WILDCARD_TEMPLATE_WHICH_CONTESTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WILDCARD TIME!.
        /// </summary>
        internal static string WILDCARD_TIME {
            get {
                return ResourceManager.GetString("WILDCARD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES!!11.
        /// </summary>
        internal static string WILDCARD_YES {
            get {
                return ResourceManager.GetString("WILDCARD_YES", resourceCulture);
            }
        }
    }
}
